{% set name = "gdk-pixbuf" %}
{% set version = "2.42.8" %}
{% set sha256 = "84acea3acb2411b29134b32015a5b1aaa62844b19c4b1ef8b8971c6b0759f4c6" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    sha256: {{ sha256 }}
    url: https://download.gnome.org/sources/{{ name }}/{{ '.'.join(version.split('.')[:2]) }}/{{ name }}-{{ version }}.tar.xz
    patches:
      - 0001-changed-perl-script-to-use-env.patch

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=gdk-pixbuf
    - {{ pin_subpackage('gdk-pixbuf', max_pin='x') }}
  ignore_run_exports:
    - zlib
    - jpeg    # [win]
    - libffi  # [win]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - meson ==0.56.2  # [osx and arm64]
    - meson >=0.55.3  # [not (osx and arm64)]
    - ninja-base
    - gobject-introspection  # [not win]
    - python
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - gobject-introspection  # [not win]
    - python
    - gettext                # [osx]
    - glib >=2.56.0
    - jpeg
    - libtiff
    - libpng
    - zlib
    - libffi >=3.3           # [win]
  run:
    - gettext                # [osx]
    - glib >=2.56.0
    - jpeg
    - libtiff
    - libpng
    - zlib
    - libffi >=3.3           # [win]

test:
  requires:
    - pkg-config
  commands:
    - gdk-pixbuf-csource --version
    - gdk-pixbuf-query-loaders
    - gdk-pixbuf-pixdata --help

    # verify that libs get installed and can be located through pkg-config
    {% set pc = "gdk-pixbuf-2.0" %}
    {% set lib = "gdk_pixbuf-2.0" %}
    - test -f $PREFIX/lib/lib{{ lib }}${SHLIB_EXT}  # [unix]
    - test -f `pkg-config --variable=libdir --dont-define-prefix {{ pc }}`/lib{{ lib }}${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\{{ lib }}-0.dll exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=exec_prefix --dont-define-prefix {{ pc }}`) do if not exist "%%a/bin/{{ lib }}-0.dll" exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\gdk_pixbuf-2.0.lib exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=libdir --dont-define-prefix {{ pc }}`) do if not exist "%%a/{{ lib }}.lib" exit 1  # [win]

about:
  home: https://www.gtk.org/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: GdkPixbuf is a library for image loading and manipulation.
  description: |
    GdkPixbuf is a library that loads image data in various formats and stores
    it as linear buffers in memory. The buffers can then be scaled, composited,
    modified, saved, or rendered.
    GdkPixbuf can load image data encoded in different formats, such as:
    PNG, JPEG, TIFF, TGA, GIF
  doc_url: https://docs.gtk.org/gdk-pixbuf/
  dev_url: https://gitlab.gnome.org/GNOME/gdk-pixbuf/

extra:
  recipe-maintainers:
    - notestaff
    - pkgw
